project_id = "avqutkamqeblqirtckir"

[functions.ohlc]
verify_jwt = false

[functions.sync-external-data]
verify_jwt = false

[functions.fetch-fund-account]
verify_jwt = false

[functions.sync-price-history]
verify_jwt = false

[functions.withdrawal-password]
verify_jwt = false

[functions.ip-geolocation]
verify_jwt = false

[functions.settle-expired-trades]
verify_jwt = false

[functions.track-login]
verify_jwt = false

[functions.admin-update-password]
verify_jwt = false

[functions.bankquay-qr]
verify_jwt = false

[functions.bankquay-webhook]
verify_jwt = false

