import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'vi' | 'en' | 'zh' | 'th' | 'ja' | 'ko' | 'id' | 'ms';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isTransitioning: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Common
    'common.loading': 'Đang tải...',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.confirm': 'Xác nhận',
    'common.delete': 'Xóa',
    'common.edit': 'Sửa',
    'common.add': 'Thêm',
    'common.search': 'Tìm kiếm',
    'common.filter': 'Lọc',
    'common.all': 'Tất cả',
    'common.viewAll': 'Xem tất cả',
    'common.back': 'Quay lại',
    'common.close': 'Đóng',
    'common.submit': 'Gửi',
    'common.status': 'Trạng thái',
    'common.details': 'Chi tiết',
    'common.copy': 'Sao chép',
    'common.settings': 'Cài đặt',
    'common.processing': 'Đang xử lý...',
    'common.error': 'Có lỗi xảy ra',
    'common.copied': 'Đã sao chép',
    
    // Navigation
    'nav.home': 'Trang chủ',
    'nav.products': 'Sản phẩm',
    'nav.news': 'Tin tức',
    'nav.charity': 'Thiện nguyện',
    'nav.profile': 'Hồ sơ',
    'nav.deposit': 'Nạp tiền',
    'nav.withdraw': 'Rút tiền',
    'nav.dashboard': 'Quản trị',
    'nav.logout': 'Đăng xuất',
    'nav.login': 'Đăng nhập',
    
    // Admin
    'admin.title': 'Quản trị',
    'admin.overview': 'Tổng quan',
    'admin.banners': 'Banners',
    'admin.news': 'Tin tức',
    'admin.products': 'Sản phẩm',
    'admin.charity': 'Từ thiện',
    'admin.transactions': 'Giao dịch',
    'admin.auditLogs': 'Audit logs',
    'admin.users': 'Người dùng',
    'admin.settings': 'Cấu hình',
    'admin.syncData': 'Đồng bộ dữ liệu',
    'admin.syncDescription': 'Đồng bộ dữ liệu từ API bên ngoài (products, news, banners, option times).',
    'admin.syncNow': 'Đồng bộ ngay',
    'admin.syncing': 'Đang đồng bộ...',
    'admin.syncSuccess': 'Đồng bộ thành công',
    'admin.syncFailed': 'Đồng bộ thất bại',
    'admin.bannerToggle': 'Bật/tắt banner toàn site',
    'admin.bannerToggleDesc': 'Hiện tại chỉ lưu cấu hình (chưa ẩn/hiện banner tự động).',
    'admin.saving': 'Đang lưu...',
    'admin.saveConfig': 'Lưu cấu hình',
    'admin.category': 'Danh mục',
    
    // Auth
    'auth.login': 'Đăng nhập',
    'auth.register': 'Đăng ký',
    'auth.email': 'Email',
    'auth.password': 'Mật khẩu',
    'auth.fullName': 'Họ và tên',
    'auth.forgotPassword': 'Quên mật khẩu?',
    'auth.noAccount': 'Chưa có tài khoản?',
    'auth.hasAccount': 'Đã có tài khoản?',
    'auth.welcomeTitle': 'Chào mừng đến ST Engineering',
    'auth.welcomeSubtitle': 'Chúc bạn có trải nghiệm tuyệt vời',
    'auth.internalPortal': 'Cổng thông tin nội bộ',
    'auth.loginByPhone': 'Đăng nhập bằng SĐT',
    'auth.loginByEmail': 'Đăng nhập bằng Email',
    'auth.registerByPhone': 'Đăng ký bằng SĐT',
    'auth.registerByEmail': 'Đăng ký bằng Email',
    'auth.phone': 'Số điện thoại',
    'auth.enterEmail': 'Nhập email của bạn',
    'auth.enterPhone': 'Nhập số điện thoại của bạn',
    'auth.enterPassword': 'Nhập mật khẩu của bạn',
    'auth.rememberMe': 'Ghi nhớ đăng nhập',
    'auth.registerHere': 'Đăng ký tại đây',
    'auth.loginHere': 'Đăng nhập tại đây',
    'auth.loggingIn': 'Đang đăng nhập...',
    'auth.registering': 'Đang đăng ký...',
    'auth.confirmPassword': 'Xác nhận mật khẩu',
    'auth.enterConfirmPassword': 'Nhập lại mật khẩu',
    'auth.agreeTerms': 'Tôi đồng ý',
    'auth.userAgreement': 'Thỏa thuận người dùng',
    'auth.privacyPolicy': 'Chính sách bảo mật',
    'auth.smartCitySolution': 'Giải pháp Thành phố Thông minh',
    'auth.smartCityDesc': 'Xây dựng hệ sinh thái đô thị thông minh nâng cao chất lượng cuộc sống thông qua tích hợp công nghệ sáng tạo.',
    'auth.learnMore': 'Tìm hiểu thêm',
    'auth.enterName': 'Nguyễn Văn A',
    'auth.emailPlaceholder': 'email@stengg.com',
    
    // Products
    'products.title': 'Sản phẩm',
    'products.featured': 'Sản phẩm nổi bật',
    'products.all': 'Tất cả sản phẩm',
    'products.buy': 'Mua',
    'products.sell': 'Bán',
    'products.price': 'Giá',
    'products.status.available': 'Còn hàng',
    'products.status.sold': 'Đã bán',
    'products.status.pending': 'Đang chờ',
    
    // Profile
    'profile.title': 'Hồ sơ cá nhân',
    'profile.balance': 'Số dư',
    'profile.totalIncome': 'Tổng thu nhập',
    'profile.transactionHistory': 'Lịch sử giao dịch',
    'profile.depositWithdraw': 'Nạp/Rút tiền',
    'profile.trade': 'Mua/Bán',
    
    // Transactions
    'transaction.deposit': 'Nạp tiền',
    'transaction.withdraw': 'Rút tiền',
    'transaction.buy': 'Mua',
    'transaction.sell': 'Bán',
    'transaction.pending': 'Đang xử lý',
    'transaction.approved': 'Hoàn thành',
    'transaction.rejected': 'Từ chối',
    'transaction.amount': 'Số tiền',
    'transaction.network': 'Mạng',
    'transaction.walletAddress': 'Địa chỉ ví',
    'transaction.noTransactions': 'Chưa có giao dịch nào',
    
    // News
    'news.title': 'Tin tức',
    'news.latest': 'Tin tức mới nhất',
    'news.readMore': 'Xem thêm',
    'news.views': 'lượt xem',
    'news.comments': 'Bình luận',
    'news.writeComment': 'Viết bình luận...',
    
    // Charity
    'charity.title': 'Chương trình thiện nguyện',
    'charity.progress': 'Tiến độ',
    'charity.target': 'Mục tiêu',
    'charity.current': 'Đã quyên góp',
    'charity.ongoing': 'Đang diễn ra',
    'charity.ended': 'Đã kết thúc',
    'charity.activePrograms': 'Chương trình đang hoạt động',
    'charity.totalDonation': 'Tổng số tiền quyên góp',
    'charity.peopleHelped': 'Người được hỗ trợ',
    'charity.description': 'ST Engineering luôn đồng hành cùng cộng đồng thông qua các chương trình từ thiện ý nghĩa. Cùng chung tay góp phần xây dựng xã hội tốt đẹp hơn.',
    
    // Deposit/Withdraw
    'deposit.title': 'Nạp tiền',
    'deposit.selectNetwork': 'Chọn mạng lưới',
    'deposit.walletAddress': 'Địa chỉ ví nhận',
    'deposit.transactionInfo': 'Thông tin giao dịch',
    'deposit.amount': 'Số tiền nạp (USDT)',
    'deposit.txHash': 'Mã giao dịch (TX Hash)',
    'deposit.enterTxHash': 'Nhập mã giao dịch sau khi chuyển',
    'deposit.confirm': 'Xác nhận nạp tiền',
    'deposit.processing': 'Đang xử lý...',
    'deposit.warning': 'Chỉ gửi USDT qua mạng này. Gửi sai mạng sẽ mất tiền.',
    'deposit.copied': 'Đã sao chép địa chỉ ví',
    'deposit.success': 'Yêu cầu nạp tiền đã được gửi thành công!',
    
    'withdraw.title': 'Rút tiền',
    'withdraw.availableBalance': 'Số dư khả dụng',
    'withdraw.withdrawInfo': 'Thông tin rút tiền',
    'withdraw.yourWallet': 'Địa chỉ ví nhận',
    'withdraw.enterWallet': 'Nhập địa chỉ ví của bạn',
    'withdraw.amount': 'Số tiền rút (USDT)',
    'withdraw.minAmount': 'Tối thiểu 10 USDT',
    'withdraw.fee': 'Phí rút (1%)',
    'withdraw.actualReceive': 'Thực nhận',
    'withdraw.confirm': 'Xác nhận rút tiền',
    'withdraw.all': 'Tất cả',
    'withdraw.processingTime': 'Thời gian xử lý: 1-24 giờ làm việc',
    'withdraw.checkAddress': 'Kiểm tra kỹ địa chỉ ví trước khi rút',
    'withdraw.wrongNetwork': 'Rút sai mạng sẽ mất tiền vĩnh viễn',
    'withdraw.success': 'Yêu cầu rút tiền đã được gửi thành công!',
    
    // Guest Home
    'guest.heroTitle': 'ST Engineering @ Singapore Airshow 2026',
    'guest.heroSubtitle': 'Đẩy mạnh thế hệ đổi mới tiếp theo',
    'guest.techTitle': 'Công nghệ định hình thế hệ đổi mới tiếp theo',
    'guest.techDesc': 'ST Engineering là tập đoàn công nghệ, quốc phòng và kỹ thuật toàn cầu với danh mục đa dạng các lĩnh vực kinh doanh bao gồm hàng không vũ trụ, thành phố thông minh, quốc phòng và an ninh công cộng. Chúng tôi khai thác công nghệ và đổi mới để giải quyết các vấn đề thực tế, tạo nên một thế giới an toàn và bền vững hơn.',
    'guest.aiTitle': 'Thúc đẩy thay đổi với sức mạnh của AI',
    'guest.aiDesc': 'ST Engineering đã bắt đầu hành trình trở thành tổ chức được hỗ trợ bởi AI thông qua lộ trình chuyển đổi AI của chúng tôi.',
    'guest.aiDesc2': 'Từ bảo trì dự đoán trong hàng không đến các giải pháp đô thị thông minh và hệ thống quốc phòng tiên tiến, AI là trọng tâm trong chiến lược đổi mới của chúng tôi.',
    'guest.readMore': 'Đọc thêm',
    'guest.enablingFuture': 'Kích hoạt tương lai của sự đổi mới',
    'guest.aviation': 'Định hình tương lai Hàng không',
    'guest.aviationDesc': 'Từ bảo trì máy bay đến các giải pháp hàng không vũ trụ sáng tạo, chúng tôi đang dẫn đầu tương lai của ngành hàng không.',
    'guest.cities': 'TƯƠNG LAI CỦA CÁC THÀNH PHỐ',
    'guest.citiesDesc': 'Các giải pháp thành phố thông minh biến đổi cuộc sống đô thị và tạo ra cộng đồng bền vững cho ngày mai.',
    'guest.security': 'Bảo vệ ngày mai, cùng nhau',
    'guest.securityDesc': 'Các giải pháp quốc phòng và an ninh tiên tiến bảo vệ những gì quan trọng nhất trong thế giới đang phát triển.',
    'guest.ctaTitle': 'Đẩy lùi giới hạn để mang đến các giải pháp đột phá',
    'guest.ctaDesc': 'Là tập đoàn kỹ thuật tích hợp toàn cầu, chúng tôi khai thác công nghệ và đổi mới để chuyển đổi các ngành công nghiệp và cải thiện cuộc sống. Từ hàng không vũ trụ đến thành phố thông minh, quốc phòng đến an ninh công cộng, chúng tôi cung cấp các giải pháp tiên tiến.',
    'guest.discover': 'Khám phá giải pháp của chúng tôi',
    'guest.aiInnovation': 'Tiên phong tương lai với các đổi mới được hỗ trợ bởi AI',
    'guest.smartCity': 'Giải pháp Thành phố Thông minh',
    'guest.smartCityTitle': 'Cơ sở hạ tầng đô thị thông minh được hỗ trợ bởi AI',
    'guest.smartCityDesc': 'Tận dụng trí tuệ nhân tạo để tạo ra cơ sở hạ tầng đô thị thông minh nâng cao hiệu quả, tính bền vững và chất lượng cuộc sống cho cư dân thành phố trên toàn thế giới.',
    'guest.cybersecurity': 'Đổi mới An ninh mạng',
    'guest.cybersecurityTitle': 'Tăng cường hoạt động An ninh mạng với AI',
    'guest.cybersecurityDesc': 'Các giải pháp an ninh mạng được hỗ trợ bởi AI tiên tiến bảo vệ cơ sở hạ tầng quan trọng và phòng thủ chống lại các mối đe dọa kỹ thuật số đang phát triển trong thời gian thực.',
    'guest.careers': 'Tuyển dụng',
    'guest.careersTitle': 'Hãy là một phần của điều tuyệt vời',
    'guest.careersDesc': 'Tham gia cùng chúng tôi tại ST Engineering, nơi đổi mới gặp gỡ mục đích. Chúng tôi đang tìm kiếm những cá nhân tài năng đam mê tạo ra sự khác biệt.',
    'guest.viewCareers': 'Xem việc làm',
    'guest.newsTitle': 'Tin tức & Cập nhật',
    'guest.innovation': 'Đổi mới',
    'guest.news1Title': 'ST Engineering Aerospace sẽ triển lãm tại Singapore Airshow 2026',
    'guest.news2Title': 'Giải pháp AI của ST Engineering giành giải thưởng Đổi mới',
    'guest.news3Title': 'Quan hệ đối tác mới thúc đẩy phát triển thành phố thông minh tại Châu Á',
    'guest.pavilionBooth': 'Gian hàng Singapore (Hall 3)',
    'guest.eventDate': 'Ngày: 6-11 Feb 2026 (Thứ Sáu-Thứ Ba)',
    'guest.hallStand': 'Vị trí gian hàng',
    // Guest Header/Footer
    'guest.global': 'Toàn cầu',
    'guest.contact': 'Liên hệ',
    'guest.support': 'Hỗ trợ',
    'guest.aboutUs': 'Về chúng tôi',
    'guest.ourBusinesses': 'Lĩnh vực kinh doanh',
    'guest.investorRelations': 'Quan hệ nhà đầu tư',
    'guest.sustainability': 'Phát triển bền vững',
    'guest.newsroom': 'Phòng tin tức',
    'guest.footerDescription': 'Tập đoàn công nghệ, quốc phòng và kỹ thuật toàn cầu.',
    'guest.companyOverview': 'Tổng quan công ty',
    'guest.leadership': 'Ban lãnh đạo',
    'guest.aerospace': 'Hàng không vũ trụ',
    'guest.defence': 'Quốc phòng & An ninh công cộng',
    'guest.digitalSystems': 'Hệ thống số',
    'guest.contactUs': 'Liên hệ chúng tôi',
    'guest.copyright': '© 2026 ST Engineering. Mọi quyền được bảo lưu.',
    'guest.termsOfUse': 'Điều khoản sử dụng',
    
    // News Categories
    'news.category.company': 'Công ty',
    'news.category.product': 'Sản phẩm',
    'news.category.event': 'Sự kiện',
    'news.category.announcement': 'Thông báo',
    'news.category.charity': 'Từ thiện',
    'news.searchPlaceholder': 'Tìm kiếm tin tức...',
    'news.noResults': 'Không tìm thấy tin tức nào.',
    'news.updateFrom': 'Cập nhật thông tin mới nhất từ ST Engineering',
    'news.viewMore': 'Xem thêm tin tức khác',
    
    // Products
    'products.noProducts': 'Không có sản phẩm nào.',
    'products.date': 'Ngày',
    'products.transactions': 'Số lượng giao dịch',
    
    // Profile
    'profile.copy': 'sao chép',
    'profile.copied': 'Đã sao chép',
    'profile.customerService': 'CSKH',
    'profile.settings': 'Cài đặt',
    'profile.invite': 'Mời bạn bè',
    'profile.update': 'Cập nhật',
    'profile.securityNotice': 'Vui lòng không tiết lộ mật khẩu, mã OTP của bạn cho bất kỳ ai',
    'profile.account': 'Tài khoản',
    'profile.security': 'Bảo mật',
    'profile.verification': 'Xác minh',
    'profile.system': 'Hệ thống',
    'profile.sync': 'Đồng bộ dữ liệu',
    'profile.uidCopied': 'Đã sao chép UID',
    
    // 404
    'notFound.title': '404',
    'notFound.message': 'Oops! Trang không tồn tại',
    'notFound.backHome': 'Quay về trang chủ',
    
    // Settings
    'settings.language': 'Ngôn ngữ',
    'settings.currency': 'Tiền tệ',
    'settings.exchangeRate': 'Tỷ giá',
  },
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.viewAll': 'View All',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.status': 'Status',
    'common.details': 'Details',
    'common.copy': 'Copy',
    'common.settings': 'Settings',
    'common.processing': 'Processing...',
    'common.error': 'An error occurred',
    'common.copied': 'Copied',
    
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.news': 'News',
    'nav.charity': 'Charity',
    'nav.profile': 'Profile',
    'nav.deposit': 'Deposit',
    'nav.withdraw': 'Withdraw',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    
    // Admin
    'admin.title': 'Administration',
    'admin.overview': 'Overview',
    'admin.banners': 'Banners',
    'admin.news': 'News',
    'admin.products': 'Products',
    'admin.charity': 'Charity',
    'admin.transactions': 'Transactions',
    'admin.auditLogs': 'Audit Logs',
    'admin.users': 'Users',
    'admin.settings': 'Settings',
    'admin.syncData': 'Sync Data',
    'admin.syncDescription': 'Sync data from external API (products, news, banners, option times).',
    'admin.syncNow': 'Sync Now',
    'admin.syncing': 'Syncing...',
    'admin.syncSuccess': 'Sync successful',
    'admin.syncFailed': 'Sync failed',
    'admin.bannerToggle': 'Enable/disable site-wide banners',
    'admin.bannerToggleDesc': 'Currently only saves configuration (does not auto-hide/show banners).',
    'admin.saving': 'Saving...',
    'admin.saveConfig': 'Save Configuration',
    'admin.category': 'Category',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.welcomeTitle': 'Welcome to ST Engineering',
    'auth.welcomeSubtitle': 'Have a great experience',
    'auth.internalPortal': 'Internal Portal',
    'auth.loginByPhone': 'Login by Phone',
    'auth.loginByEmail': 'Login by Email',
    'auth.registerByPhone': 'Register by Phone',
    'auth.registerByEmail': 'Register by Email',
    'auth.phone': 'Phone Number',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPhone': 'Enter your phone number',
    'auth.enterPassword': 'Enter your password',
    'auth.rememberMe': 'Remember me',
    'auth.registerHere': 'Register here',
    'auth.loginHere': 'Login here',
    'auth.loggingIn': 'Logging in...',
    'auth.registering': 'Registering...',
    'auth.confirmPassword': 'Confirm Password',
    'auth.enterConfirmPassword': 'Re-enter password',
    'auth.agreeTerms': 'I agree to',
    'auth.userAgreement': 'User Agreement',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.smartCitySolution': 'Smart City Solutions',
    'auth.smartCityDesc': 'Building a smart urban ecosystem that enhances quality of life through innovative technology integration.',
    'auth.learnMore': 'Learn more',
    'auth.enterName': 'John Doe',
    'auth.emailPlaceholder': 'email@stengg.com',
    
    // Products
    'products.title': 'Products',
    'products.featured': 'Featured Products',
    'products.all': 'All Products',
    'products.buy': 'Buy',
    'products.sell': 'Sell',
    'products.price': 'Price',
    'products.status.available': 'Available',
    'products.status.sold': 'Sold',
    'products.status.pending': 'Pending',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.balance': 'Balance',
    'profile.totalIncome': 'Total Income',
    'profile.transactionHistory': 'Transaction History',
    'profile.depositWithdraw': 'Deposit/Withdraw',
    'profile.trade': 'Buy/Sell',
    
    // Transactions
    'transaction.deposit': 'Deposit',
    'transaction.withdraw': 'Withdraw',
    'transaction.buy': 'Buy',
    'transaction.sell': 'Sell',
    'transaction.pending': 'Pending',
    'transaction.approved': 'Completed',
    'transaction.rejected': 'Rejected',
    'transaction.amount': 'Amount',
    'transaction.network': 'Network',
    'transaction.walletAddress': 'Wallet Address',
    'transaction.noTransactions': 'No transactions yet',
    
    // News
    'news.title': 'News',
    'news.latest': 'Latest News',
    'news.readMore': 'Read More',
    'news.views': 'views',
    'news.comments': 'Comments',
    'news.writeComment': 'Write a comment...',
    
    // Charity
    'charity.title': 'Charity Programs',
    'charity.progress': 'Progress',
    'charity.target': 'Target',
    'charity.current': 'Raised',
    'charity.ongoing': 'Ongoing',
    'charity.ended': 'Ended',
    'charity.activePrograms': 'Active Programs',
    'charity.totalDonation': 'Total Donations',
    'charity.peopleHelped': 'People Helped',
    'charity.description': 'ST Engineering is always with the community through meaningful charity programs. Join us in building a better society.',
    
    // Deposit/Withdraw
    'deposit.title': 'Deposit',
    'deposit.selectNetwork': 'Select Network',
    'deposit.walletAddress': 'Receiving Wallet Address',
    'deposit.transactionInfo': 'Transaction Information',
    'deposit.amount': 'Deposit Amount (USDT)',
    'deposit.txHash': 'Transaction Hash (TX Hash)',
    'deposit.enterTxHash': 'Enter transaction hash after transfer',
    'deposit.confirm': 'Confirm Deposit',
    'deposit.processing': 'Processing...',
    'deposit.warning': 'Only send USDT via this network. Sending via wrong network will result in loss.',
    'deposit.copied': 'Wallet address copied',
    'deposit.success': 'Deposit request submitted successfully!',
    
    'withdraw.title': 'Withdraw',
    'withdraw.availableBalance': 'Available Balance',
    'withdraw.withdrawInfo': 'Withdrawal Information',
    'withdraw.yourWallet': 'Receiving Wallet Address',
    'withdraw.enterWallet': 'Enter your wallet address',
    'withdraw.amount': 'Withdrawal Amount (USDT)',
    'withdraw.minAmount': 'Minimum 10 USDT',
    'withdraw.fee': 'Withdrawal Fee (1%)',
    'withdraw.actualReceive': 'Actual Received',
    'withdraw.confirm': 'Confirm Withdrawal',
    'withdraw.all': 'All',
    'withdraw.processingTime': 'Processing time: 1-24 business hours',
    'withdraw.checkAddress': 'Double check wallet address before withdrawing',
    'withdraw.wrongNetwork': 'Withdrawing to wrong network will result in permanent loss',
    'withdraw.success': 'Withdrawal request submitted successfully!',
    
    // Guest Home
    'guest.heroTitle': 'ST Engineering @ Singapore Airshow 2026',
    'guest.heroSubtitle': 'Pushing the next generation of innovation',
    'guest.techTitle': 'Technology shaping the next generation of innovation',
    'guest.techDesc': 'ST Engineering is a global technology, defence and engineering group with a diverse portfolio of businesses across the aerospace, smart city, defence and public security segments. We harness technology and innovation to solve real-world problems, enabling a more secure and sustainable world.',
    'guest.aiTitle': 'Enabling change with the power of AI',
    'guest.aiDesc': 'ST Engineering has embarked on a journey to become an AI-enabled organisation through our AI transformation roadmap.',
    'guest.aiDesc2': 'From predictive maintenance in aerospace to smart urban solutions and advanced defence systems, AI is central to our innovation strategy.',
    'guest.readMore': 'Read More',
    'guest.enablingFuture': 'Enabling the future of innovation',
    'guest.aviation': 'Shaping the future of Aviation',
    'guest.aviationDesc': 'From aircraft maintenance to innovative aerospace solutions, we\'re driving the future of flight.',
    'guest.cities': 'FUTURE OF THE CITIES',
    'guest.citiesDesc': 'Smart city solutions that transform urban living and create sustainable communities for tomorrow.',
    'guest.security': 'Securing tomorrow, together',
    'guest.securityDesc': 'Advanced defence and security solutions protecting what matters most in an evolving world.',
    'guest.ctaTitle': 'Pushing boundaries to deliver game-changing solutions',
    'guest.ctaDesc': 'As a global integrated engineering group, we harness technology and innovation to transform industries and improve lives. From aerospace to smart cities, defence to public security, we deliver cutting-edge solutions.',
    'guest.discover': 'Discover our solutions',
    'guest.aiInnovation': 'Pioneering the future with AI-powered innovations',
    'guest.smartCity': 'Smart City Solutions',
    'guest.smartCityTitle': 'AI-Driven Urban Infrastructure for Smarter Cities',
    'guest.smartCityDesc': 'Leveraging artificial intelligence to create intelligent urban infrastructure that enhances efficiency, sustainability, and quality of life for city dwellers worldwide.',
    'guest.cybersecurity': 'Cybersecurity Innovation',
    'guest.cybersecurityTitle': 'Powering Cybersecurity Operations with AI',
    'guest.cybersecurityDesc': 'Advanced AI-powered cybersecurity solutions that protect critical infrastructure and defend against evolving digital threats in real-time.',
    'guest.careers': 'Careers',
    'guest.careersTitle': 'Be part of something great',
    'guest.careersDesc': 'Join us at ST Engineering, where innovation meets purpose. We\'re looking for talented individuals who are passionate about making a difference.',
    'guest.viewCareers': 'View Careers',
    'guest.newsTitle': 'News and Updates',
    'guest.innovation': 'Innovation',
    'guest.news1Title': 'ST Engineering Aerospace to exhibit at Singapore Airshow 2026',
    'guest.news2Title': 'ST Engineering\'s AI-powered solutions win Innovation Award',
    'guest.news3Title': 'New partnership to advance smart city development in Asia',
    'guest.pavilionBooth': 'Singapore Pavilion booths (Hall 3)',
    'guest.eventDate': 'Date: 6-11 Feb 2026 (Fri-Tue)',
    'guest.hallStand': 'Hall Stand',
    // Guest Header/Footer
    'guest.global': 'Global',
    'guest.contact': 'Contact',
    'guest.support': 'Support',
    'guest.aboutUs': 'About Us',
    'guest.ourBusinesses': 'Our Businesses',
    'guest.investorRelations': 'Investor Relations',
    'guest.sustainability': 'Sustainability',
    'guest.newsroom': 'Newsroom',
    'guest.footerDescription': 'A global technology, defence and engineering group.',
    'guest.companyOverview': 'Company Overview',
    'guest.leadership': 'Leadership',
    'guest.aerospace': 'Aerospace',
    'guest.defence': 'Defence & Public Security',
    'guest.digitalSystems': 'Digital Systems',
    'guest.contactUs': 'Contact Us',
    'guest.copyright': '© 2026 ST Engineering. All rights reserved.',
    'guest.termsOfUse': 'Terms of Use',
    
    // News Categories
    'news.category.company': 'Company',
    'news.category.product': 'Product',
    'news.category.event': 'Event',
    'news.category.announcement': 'Announcement',
    'news.category.charity': 'Charity',
    'news.searchPlaceholder': 'Search news...',
    'news.noResults': 'No news found.',
    'news.updateFrom': 'Latest updates from ST Engineering',
    'news.viewMore': 'View more news',
    
    // Products
    'products.noProducts': 'No products available.',
    'products.date': 'Date',
    'products.transactions': 'Transaction Volume',
    
    // Profile
    'profile.copy': 'copy',
    'profile.copied': 'Copied',
    'profile.customerService': 'Support',
    'profile.settings': 'Settings',
    'profile.invite': 'Invite Friends',
    'profile.update': 'Update',
    'profile.securityNotice': 'Please do not share your password or OTP with anyone',
    'profile.account': 'Account',
    'profile.security': 'Security',
    'profile.verification': 'Verification',
    'profile.system': 'System',
    'profile.sync': 'Sync Data',
    'profile.uidCopied': 'UID copied',
    
    // 404
    'notFound.title': '404',
    'notFound.message': 'Oops! Page not found',
    'notFound.backHome': 'Return to Home',
    
    // Settings
    'settings.language': 'Language',
    'settings.currency': 'Currency',
    'settings.exchangeRate': 'Exchange Rate',
  },
  zh: {
    // Common
    'common.loading': '加载中...',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.add': '添加',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.all': '全部',
    'common.viewAll': '查看全部',
    'common.back': '返回',
    'common.close': '关闭',
    'common.submit': '提交',
    'common.status': '状态',
    'common.details': '详情',
    'common.copy': '复制',
    'common.settings': '设置',
    'common.processing': '处理中...',
    'common.error': '发生错误',
    'common.copied': '已复制',
    
    // Navigation
    'nav.home': '首页',
    'nav.products': '产品',
    'nav.news': '新闻',
    'nav.charity': '慈善',
    'nav.profile': '个人资料',
    'nav.deposit': '充值',
    'nav.withdraw': '提现',
    'nav.dashboard': '管理后台',
    'nav.logout': '退出登录',
    'nav.login': '登录',
    
    // Admin
    'admin.title': '管理',
    'admin.overview': '概览',
    'admin.banners': '横幅',
    'admin.news': '新闻',
    'admin.products': '产品',
    'admin.charity': '慈善',
    'admin.transactions': '交易',
    'admin.auditLogs': '审计日志',
    'admin.users': '用户',
    'admin.settings': '设置',
    'admin.syncData': '同步数据',
    'admin.syncDescription': '从外部API同步数据（产品、新闻、横幅、选项时间）。',
    'admin.syncNow': '立即同步',
    'admin.syncing': '同步中...',
    'admin.syncSuccess': '同步成功',
    'admin.syncFailed': '同步失败',
    'admin.bannerToggle': '启用/禁用全站横幅',
    'admin.bannerToggleDesc': '目前仅保存配置（不自动隐藏/显示横幅）。',
    'admin.saving': '保存中...',
    'admin.saveConfig': '保存配置',
    'admin.category': '分类',
    
    // News
    'news.viewMore': '查看更多新闻',
    
    // Auth
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.fullName': '姓名',
    'auth.forgotPassword': '忘记密码？',
    'auth.noAccount': '还没有账号？',
    'auth.hasAccount': '已有账号？',
    'auth.welcomeTitle': '欢迎来到ST Engineering',
    'auth.welcomeSubtitle': '祝您有美好的体验',
    'auth.internalPortal': '内部门户',
    'auth.loginByPhone': '手机登录',
    'auth.loginByEmail': '邮箱登录',
    'auth.registerByPhone': '手机注册',
    'auth.registerByEmail': '邮箱注册',
    'auth.phone': '手机号码',
    'auth.enterEmail': '请输入邮箱',
    'auth.enterPhone': '请输入手机号',
    'auth.enterPassword': '请输入密码',
    'auth.rememberMe': '记住登录',
    'auth.registerHere': '立即注册',
    'auth.loginHere': '立即登录',
    'auth.loggingIn': '登录中...',
    'auth.registering': '注册中...',
    'auth.confirmPassword': '确认密码',
    'auth.enterConfirmPassword': '请再次输入密码',
    'auth.agreeTerms': '我同意',
    'auth.userAgreement': '用户协议',
    'auth.privacyPolicy': '隐私政策',
    'auth.smartCitySolution': '智慧城市解决方案',
    'auth.smartCityDesc': '通过创新技术集成构建智慧城市生态系统，提升生活品质。',
    'auth.learnMore': '了解更多',
    'auth.enterName': '张三',
    'auth.emailPlaceholder': 'email@stengg.com',
    
    // Products
    'products.title': '产品',
    'products.featured': '精选产品',
    'products.all': '全部产品',
    'products.buy': '购买',
    'products.sell': '出售',
    'products.price': '价格',
    'products.status.available': '可购买',
    'products.status.sold': '已售出',
    'products.status.pending': '待处理',
    
    // Profile
    'profile.title': '个人资料',
    'profile.balance': '余额',
    'profile.totalIncome': '总收入',
    'profile.transactionHistory': '交易记录',
    'profile.depositWithdraw': '充值/提现',
    'profile.trade': '买入/卖出',
    
    // Transactions
    'transaction.deposit': '充值',
    'transaction.withdraw': '提现',
    'transaction.buy': '买入',
    'transaction.sell': '卖出',
    'transaction.pending': '处理中',
    'transaction.approved': '已完成',
    'transaction.rejected': '已拒绝',
    'transaction.amount': '金额',
    'transaction.network': '网络',
    'transaction.walletAddress': '钱包地址',
    'transaction.noTransactions': '暂无交易记录',
    
    // News
    'news.title': '新闻',
    'news.latest': '最新新闻',
    'news.readMore': '阅读更多',
    'news.views': '浏览',
    'news.comments': '评论',
    'news.writeComment': '写评论...',
    
    // Charity
    'charity.title': '慈善项目',
    'charity.progress': '进度',
    'charity.target': '目标',
    'charity.current': '已筹集',
    'charity.ongoing': '进行中',
    'charity.ended': '已结束',
    'charity.activePrograms': '活跃项目',
    'charity.totalDonation': '捐款总额',
    'charity.peopleHelped': '受助人数',
    'charity.description': 'ST Engineering始终与社区同行，通过有意义的慈善项目。让我们共同建设更美好的社会。',
    
    // Deposit/Withdraw
    'deposit.title': '充值',
    'deposit.selectNetwork': '选择网络',
    'deposit.walletAddress': '接收钱包地址',
    'deposit.transactionInfo': '交易信息',
    'deposit.amount': '充值金额 (USDT)',
    'deposit.txHash': '交易哈希',
    'deposit.confirm': '确认充值',
    'deposit.processing': '处理中...',
    'withdraw.title': '提现',
    'withdraw.availableBalance': '可用余额',
    'withdraw.confirm': '确认提现',
    'withdraw.all': '全部',
    
    // Guest/News/Products
    'guest.heroTitle': 'ST Engineering @ 新加坡航展 2026',
    'guest.heroSubtitle': '推动下一代创新',
    'guest.techTitle': '塑造下一代创新的技术',
    'guest.techDesc': 'ST Engineering是一家全球科技、国防和工程集团，在航空航天、智慧城市、国防和公共安全领域拥有多元化业务组合。我们利用技术和创新解决现实问题，创造更安全、更可持续的世界。',
    'guest.aiTitle': '用AI的力量推动变革',
    'guest.aiDesc': 'ST Engineering已踏上成为AI驱动组织的旅程，通过我们的AI转型路线图。',
    'guest.aiDesc2': '从航空航天的预测性维护到智慧城市解决方案和先进国防系统，AI是我们创新战略的核心。',
    'guest.readMore': '阅读更多',
    'guest.enablingFuture': '开启创新的未来',
    'guest.aviation': '塑造航空的未来',
    'guest.aviationDesc': '从飞机维护到创新航空航天解决方案，我们正在引领飞行的未来。',
    'guest.cities': '城市的未来',
    'guest.citiesDesc': '智慧城市解决方案改变城市生活，为明天创造可持续社区。',
    'guest.security': '共同守护明天',
    'guest.securityDesc': '先进的国防和安全解决方案，在不断发展的世界中保护最重要的事物。',
    'guest.ctaTitle': '突破边界，提供颠覆性解决方案',
    'guest.ctaDesc': '作为全球综合工程集团，我们利用技术和创新改变行业、改善生活。从航空航天到智慧城市，从国防到公共安全，我们提供尖端解决方案。',
    'guest.discover': '探索我们的解决方案',
    'guest.aiInnovation': '用AI驱动的创新开拓未来',
    'guest.smartCity': '智慧城市解决方案',
    'guest.smartCityTitle': 'AI驱动的智慧城市基础设施',
    'guest.smartCityDesc': '利用人工智能创建智能城市基础设施，提高全球城市居民的效率、可持续性和生活质量。',
    'guest.cybersecurity': '网络安全创新',
    'guest.cybersecurityTitle': '用AI强化网络安全运营',
    'guest.cybersecurityDesc': '先进的AI驱动网络安全解决方案，实时保护关键基础设施并防御不断演变的数字威胁。',
    'guest.careers': '招聘',
    'guest.careersTitle': '成为伟大的一部分',
    'guest.careersDesc': '加入ST Engineering，在这里创新与目标相遇。我们正在寻找有才华、热衷于创造改变的人。',
    'guest.viewCareers': '查看职位',
    'guest.newsTitle': '新闻与更新',
    'guest.innovation': '创新',
    'guest.news1Title': 'ST Engineering航空将在2026年新加坡航展上展出',
    'guest.news2Title': 'ST Engineering的AI解决方案获得创新奖',
    'guest.news3Title': '新合作伙伴关系推进亚洲智慧城市发展',
    'guest.pavilionBooth': '新加坡馆展位（3号馆）',
    'guest.eventDate': '日期：2026年2月6-11日（周五至周二）',
    'guest.hallStand': '展位位置',
    'guest.global': '全球',
    'guest.contact': '联系',
    'guest.support': '支持',
    'guest.aboutUs': '关于我们',
    'guest.ourBusinesses': '业务领域',
    'guest.investorRelations': '投资者关系',
    'guest.sustainability': '可持续发展',
    'guest.newsroom': '新闻室',
    'guest.footerDescription': '全球科技、国防和工程集团。',
    'guest.companyOverview': '公司概况',
    'guest.leadership': '领导团队',
    'guest.aerospace': '航空航天',
    'guest.defence': '国防与公共安全',
    'guest.digitalSystems': '数字系统',
    'guest.contactUs': '联系我们',
    'guest.copyright': '© 2026 ST Engineering. 保留所有权利。',
    'guest.termsOfUse': '使用条款',
    'news.category.company': '公司',
    'news.category.product': '产品',
    'news.category.event': '活动',
    'news.category.announcement': '公告',
    'news.category.charity': '慈善',
    'news.searchPlaceholder': '搜索新闻...',
    'news.noResults': '未找到新闻。',
    'products.noProducts': '暂无产品。',
    'products.date': '日期',
    'products.transactions': '交易量',
    'profile.copy': '复制',
    'profile.copied': '已复制',
    'profile.account': '账户',
    'profile.security': '安全',
    'profile.verification': '验证',
    'profile.system': '系统',
    'profile.sync': '同步数据',
    'profile.uidCopied': 'UID已复制',
    'profile.customerService': '客服',
    'profile.settings': '设置',
    'profile.invite': '邀请好友',
    'profile.update': '更新',
    'profile.securityNotice': '请勿向任何人透露您的密码或OTP',
    'notFound.title': '404',
    'notFound.message': '页面未找到',
    'notFound.backHome': '返回首页',
    
    // Settings
    'settings.language': '语言',
    'settings.currency': '货币',
    'settings.exchangeRate': '汇率',
  },
  th: {
    // Common
    'common.loading': 'กำลังโหลด...',
    'common.save': 'บันทึก',
    'common.cancel': 'ยกเลิก',
    'common.confirm': 'ยืนยัน',
    'common.delete': 'ลบ',
    'common.edit': 'แก้ไข',
    'common.add': 'เพิ่ม',
    'common.search': 'ค้นหา',
    'common.filter': 'กรอง',
    'common.all': 'ทั้งหมด',
    'common.viewAll': 'ดูทั้งหมด',
    'common.back': 'กลับ',
    'common.close': 'ปิด',
    'common.submit': 'ส่ง',
    'common.status': 'สถานะ',
    'common.details': 'รายละเอียด',
    'common.copy': 'คัดลอก',
    'common.settings': 'ตั้งค่า',
    'common.processing': 'กำลังดำเนินการ...',
    'common.error': 'เกิดข้อผิดพลาด',
    'common.copied': 'คัดลอกแล้ว',
    
    // Navigation
    'nav.home': 'หน้าแรก',
    'nav.products': 'สินค้า',
    'nav.news': 'ข่าวสาร',
    'nav.charity': 'การกุศล',
    'nav.profile': 'โปรไฟล์',
    'nav.deposit': 'ฝากเงิน',
    'nav.withdraw': 'ถอนเงิน',
    'nav.dashboard': 'แดชบอร์ด',
    'nav.logout': 'ออกจากระบบ',
    'nav.login': 'เข้าสู่ระบบ',
    
    // Auth
    'auth.login': 'เข้าสู่ระบบ',
    'auth.register': 'ลงทะเบียน',
    'auth.email': 'อีเมล',
    'auth.password': 'รหัสผ่าน',
    'auth.fullName': 'ชื่อ-นามสกุล',
    'auth.forgotPassword': 'ลืมรหัสผ่าน?',
    'auth.noAccount': 'ยังไม่มีบัญชี?',
    'auth.hasAccount': 'มีบัญชีแล้ว?',
    'auth.welcomeTitle': 'ยินดีต้อนรับสู่ ST Engineering',
    'auth.welcomeSubtitle': 'ขอให้คุณมีประสบการณ์ที่ดี',
    'auth.internalPortal': 'พอร์ทัลภายใน',
    'auth.loginByPhone': 'เข้าสู่ระบบด้วยโทรศัพท์',
    'auth.loginByEmail': 'เข้าสู่ระบบด้วยอีเมล',
    'auth.registerByPhone': 'ลงทะเบียนด้วยโทรศัพท์',
    'auth.registerByEmail': 'ลงทะเบียนด้วยอีเมล',
    'auth.phone': 'หมายเลขโทรศัพท์',
    'auth.enterEmail': 'กรอกอีเมลของคุณ',
    'auth.enterPhone': 'กรอกเบอร์โทรศัพท์ของคุณ',
    'auth.enterPassword': 'กรอกรหัสผ่านของคุณ',
    'auth.rememberMe': 'จดจำการเข้าสู่ระบบ',
    'auth.registerHere': 'ลงทะเบียนที่นี่',
    'auth.loginHere': 'เข้าสู่ระบบที่นี่',
    'auth.loggingIn': 'กำลังเข้าสู่ระบบ...',
    'auth.registering': 'กำลังลงทะเบียน...',
    'auth.confirmPassword': 'ยืนยันรหัสผ่าน',
    'auth.enterConfirmPassword': 'กรอกรหัสผ่านอีกครั้ง',
    'auth.agreeTerms': 'ฉันยอมรับ',
    'auth.userAgreement': 'ข้อตกลงผู้ใช้',
    'auth.privacyPolicy': 'นโยบายความเป็นส่วนตัว',
    'auth.smartCitySolution': 'โซลูชันเมืองอัจฉริยะ',
    'auth.smartCityDesc': 'สร้างระบบนิเวศเมืองอัจฉริยะที่ยกระดับคุณภาพชีวิตผ่านการบูรณาการเทคโนโลยี',
    'auth.learnMore': 'เรียนรู้เพิ่มเติม',
    'auth.enterName': 'สมชาย ใจดี',
    'auth.emailPlaceholder': 'email@stengg.com',
    
    // Products
    'products.title': 'สินค้า',
    'products.featured': 'สินค้าแนะนำ',
    'products.all': 'สินค้าทั้งหมด',
    'products.buy': 'ซื้อ',
    'products.sell': 'ขาย',
    'products.price': 'ราคา',
    'products.status.available': 'มีสินค้า',
    'products.status.sold': 'ขายแล้ว',
    'products.status.pending': 'รอดำเนินการ',
    
    // Profile
    'profile.title': 'โปรไฟล์ของฉัน',
    'profile.balance': 'ยอดคงเหลือ',
    'profile.totalIncome': 'รายได้รวม',
    'profile.transactionHistory': 'ประวัติธุรกรรม',
    'profile.depositWithdraw': 'ฝาก/ถอน',
    'profile.trade': 'ซื้อ/ขาย',
    
    // Transactions
    'transaction.deposit': 'ฝากเงิน',
    'transaction.withdraw': 'ถอนเงิน',
    'transaction.buy': 'ซื้อ',
    'transaction.sell': 'ขาย',
    'transaction.pending': 'รอดำเนินการ',
    'transaction.approved': 'สำเร็จ',
    'transaction.rejected': 'ถูกปฏิเสธ',
    'transaction.amount': 'จำนวน',
    'transaction.network': 'เครือข่าย',
    'transaction.walletAddress': 'ที่อยู่กระเป๋าเงิน',
    'transaction.noTransactions': 'ยังไม่มีธุรกรรม',
    
    // News
    'news.title': 'ข่าวสาร',
    'news.latest': 'ข่าวล่าสุด',
    'news.readMore': 'อ่านเพิ่มเติม',
    'news.views': 'ครั้ง',
    'news.comments': 'ความคิดเห็น',
    'news.writeComment': 'เขียนความคิดเห็น...',
    
    // Charity
    'charity.title': 'โครงการการกุศล',
    'charity.progress': 'ความคืบหน้า',
    'charity.target': 'เป้าหมาย',
    'charity.current': 'ระดมทุนได้',
    'charity.ongoing': 'กำลังดำเนินการ',
    'charity.ended': 'สิ้นสุดแล้ว',
    'deposit.title': 'ฝากเงิน',
    'deposit.confirm': 'ยืนยันการฝากเงิน',
    'withdraw.title': 'ถอนเงิน',
    'withdraw.confirm': 'ยืนยันการถอนเงิน',
    'news.searchPlaceholder': 'ค้นหาข่าว...',
    'news.noResults': 'ไม่พบข่าว',
    'products.noProducts': 'ไม่มีสินค้า',
    'notFound.title': '404',
    'notFound.message': 'ไม่พบหน้านี้',
    'notFound.backHome': 'กลับหน้าหลัก',
    // Guest Home
    'guest.heroTitle': 'ST Engineering @ Singapore Airshow 2026',
    'guest.heroSubtitle': 'ขับเคลื่อนนวัตกรรมรุ่นต่อไป',
    'guest.techTitle': 'เทคโนโลยีที่กำหนดรูปแบบนวัตกรรมแห่งอนาคต',
    'guest.techDesc': 'ST Engineering เป็นกลุ่มบริษัทเทคโนโลยี การป้องกัน และวิศวกรรมระดับโลก ที่มีพอร์ตโฟลิโอหลากหลายในด้านการบินและอวกาศ เมืองอัจฉริยะ การป้องกันประเทศ และความปลอดภัยสาธารณะ เราใช้เทคโนโลยีและนวัตกรรมเพื่อแก้ปัญหาในโลกจริง สร้างโลกที่ปลอดภัยและยั่งยืนมากขึ้น',
    'guest.aiTitle': 'ขับเคลื่อนการเปลี่ยนแปลงด้วยพลังของ AI',
    'guest.aiDesc': 'ST Engineering ได้เริ่มต้นเส้นทางสู่การเป็นองค์กรที่ขับเคลื่อนด้วย AI ผ่านแผนงานการเปลี่ยนแปลง AI ของเรา',
    'guest.aiDesc2': 'ตั้งแต่การบำรุงรักษาเชิงพยากรณ์ในด้านการบินไปจนถึงโซลูชันเมืองอัจฉริยะและระบบป้องกันขั้นสูง AI เป็นหัวใจของกลยุทธ์นวัตกรรมของเรา',
    'guest.readMore': 'อ่านเพิ่มเติม',
    'guest.enablingFuture': 'เปิดทางสู่อนาคตของนวัตกรรม',
    'guest.aviation': 'กำหนดอนาคตของการบิน',
    'guest.aviationDesc': 'ตั้งแต่การบำรุงรักษาอากาศยานไปจนถึงโซลูชันการบินและอวกาศที่สร้างสรรค์ เราเป็นผู้นำอนาคตของการบิน',
    'guest.cities': 'อนาคตของเมือง',
    'guest.citiesDesc': 'โซลูชันเมืองอัจฉริยะที่เปลี่ยนแปลงชีวิตในเมืองและสร้างชุมชนที่ยั่งยืนสำหรับวันพรุ่งนี้',
    'guest.security': 'ปกป้องวันพรุ่งนี้ ไปด้วยกัน',
    'guest.securityDesc': 'โซลูชันการป้องกันและความปลอดภัยขั้นสูงที่ปกป้องสิ่งที่สำคัญที่สุดในโลกที่กำลังเปลี่ยนแปลง',
    'guest.ctaTitle': 'ผลักดันขีดจำกัดเพื่อส่งมอบโซลูชันที่เปลี่ยนเกม',
    'guest.ctaDesc': 'ในฐานะกลุ่มวิศวกรรมบูรณาการระดับโลก เราใช้เทคโนโลยีและนวัตกรรมเพื่อเปลี่ยนแปลงอุตสาหกรรมและปรับปรุงชีวิต ตั้งแต่การบินและอวกาศไปจนถึงเมืองอัจฉริยะ การป้องกันไปจนถึงความปลอดภัยสาธารณะ เราส่งมอบโซลูชันล้ำสมัย',
    'guest.discover': 'ค้นพบโซลูชันของเรา',
    'guest.aiInnovation': 'บุกเบิกอนาคตด้วยนวัตกรรมที่ขับเคลื่อนด้วย AI',
    'guest.smartCityTitle': 'โครงสร้างพื้นฐานเมืองอัจฉริยะที่ขับเคลื่อนด้วย AI',
    'guest.smartCityDesc': 'ใช้ประโยชน์จากปัญญาประดิษฐ์เพื่อสร้างโครงสร้างพื้นฐานเมืองอัจฉริยะที่เพิ่มประสิทธิภาพ ความยั่งยืน และคุณภาพชีวิตสำหรับผู้อยู่อาศัยในเมืองทั่วโลก',
    'guest.cybersecurity': 'นวัตกรรมความปลอดภัยไซเบอร์',
    'guest.cybersecurityTitle': 'เสริมพลังปฏิบัติการความปลอดภัยไซเบอร์ด้วย AI',
    'guest.cybersecurityDesc': 'โซลูชันความปลอดภัยไซเบอร์ที่ขับเคลื่อนด้วย AI ขั้นสูงที่ปกป้องโครงสร้างพื้นฐานที่สำคัญและป้องกันภัยคุกคามดิจิทัลที่กำลังพัฒนาแบบเรียลไทม์',
    'guest.careersTitle': 'มาเป็นส่วนหนึ่งของสิ่งที่ยิ่งใหญ่',
    'guest.careersDesc': 'เข้าร่วมกับเราที่ ST Engineering ที่ซึ่งนวัตกรรมพบกับเป้าหมาย เรากำลังมองหาบุคคลที่มีความสามารถที่มีความหลงใหลในการสร้างความแตกต่าง',
    'guest.viewCareers': 'ดูตำแหน่งงาน',
    'guest.newsTitle': 'ข่าวสารและอัปเดต',
    'guest.innovation': 'นวัตกรรม',
    'guest.news1Title': 'ST Engineering Aerospace จะจัดแสดงที่งาน Singapore Airshow 2026',
    'guest.news2Title': 'โซลูชัน AI ของ ST Engineering คว้ารางวัลนวัตกรรม',
    'guest.news3Title': 'พันธมิตรใหม่เพื่อขับเคลื่อนการพัฒนาเมืองอัจฉริยะในเอเชีย',
    'guest.pavilionBooth': 'บูธ Singapore Pavilion (ฮอลล์ 3)',
    'guest.eventDate': 'วันที่: 6-11 ก.พ. 2026 (ศ.-อ.)',
    'guest.hallStand': 'ตำแหน่งบูธ',
    // Guest Header/Footer
    'guest.global': 'ทั่วโลก',
    'guest.contact': 'ติดต่อ',
    'guest.support': 'สนับสนุน',
    'guest.aboutUs': 'เกี่ยวกับเรา',
    'guest.ourBusinesses': 'ธุรกิจของเรา',
    'guest.investorRelations': 'นักลงทุนสัมพันธ์',
    'guest.sustainability': 'ความยั่งยืน',
    'guest.newsroom': 'ห้องข่าว',
    'guest.careers': 'ร่วมงานกับเรา',
    'guest.footerDescription': 'กลุ่มเทคโนโลยี ความมั่นคง และวิศวกรรมระดับโลก',
    'guest.companyOverview': 'ภาพรวมบริษัท',
    'guest.leadership': 'ผู้บริหาร',
    'guest.aerospace': 'การบินและอวกาศ',
    'guest.smartCity': 'เมืองอัจฉริยะ',
    'guest.defence': 'กลาโหมและความมั่นคงสาธารณะ',
    'guest.digitalSystems': 'ระบบดิจิทัล',
    'guest.contactUs': 'ติดต่อเรา',
    'guest.copyright': '© 2026 ST Engineering สงวนลิขสิทธิ์',
    'guest.termsOfUse': 'ข้อกำหนดการใช้งาน',
    // Profile
    'profile.copy': 'คัดลอก',
    'profile.copied': 'คัดลอกแล้ว',
    'profile.account': 'บัญชี',
    'profile.security': 'ความปลอดภัย',
    'profile.verification': 'การยืนยัน',
    'profile.system': 'ระบบ',
    'profile.sync': 'ซิงค์ข้อมูล',
    'profile.uidCopied': 'คัดลอก UID แล้ว',
    'profile.customerService': 'ฝ่ายบริการ',
    'profile.settings': 'ตั้งค่า',
    'profile.invite': 'เชิญเพื่อน',
    'profile.update': 'อัปเดต',
    'profile.securityNotice': 'กรุณาอย่าเปิดเผยรหัสผ่านหรือ OTP ให้ผู้อื่น',
    // Settings
    'settings.language': 'ภาษา',
    'settings.currency': 'สกุลเงิน',
    'settings.exchangeRate': 'อัตราแลกเปลี่ยน',
  },
  ja: {
    // Common
    'common.loading': '読み込み中...',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.confirm': '確認',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.add': '追加',
    'common.search': '検索',
    'common.filter': 'フィルター',
    'common.all': 'すべて',
    'common.viewAll': 'すべて見る',
    'common.back': '戻る',
    'common.close': '閉じる',
    'common.submit': '送信',
    'common.status': 'ステータス',
    'common.details': '詳細',
    'common.copy': 'コピー',
    'common.settings': '設定',
    'common.processing': '処理中...',
    'common.error': 'エラーが発生しました',
    'common.copied': 'コピーしました',
    
    // Navigation
    'nav.home': 'ホーム',
    'nav.products': '製品',
    'nav.news': 'ニュース',
    'nav.charity': 'チャリティ',
    'nav.profile': 'プロフィール',
    'nav.deposit': '入金',
    'nav.withdraw': '出金',
    'nav.dashboard': 'ダッシュボード',
    'nav.logout': 'ログアウト',
    'nav.login': 'ログイン',
    
    // Auth
    'auth.login': 'ログイン',
    'auth.register': '登録',
    'auth.email': 'メール',
    'auth.password': 'パスワード',
    'auth.fullName': '氏名',
    'auth.forgotPassword': 'パスワードをお忘れですか？',
    'auth.noAccount': 'アカウントをお持ちでない方',
    'auth.hasAccount': 'アカウントをお持ちの方',
    'auth.welcomeTitle': 'ST Engineeringへようこそ',
    'auth.welcomeSubtitle': '素晴らしい体験をお楽しみください',
    'auth.internalPortal': '社内ポータル',
    'auth.loginByPhone': '電話でログイン',
    'auth.loginByEmail': 'メールでログイン',
    'auth.registerByPhone': '電話で登録',
    'auth.registerByEmail': 'メールで登録',
    'auth.phone': '電話番号',
    'auth.enterEmail': 'メールアドレスを入力',
    'auth.enterPhone': '電話番号を入力',
    'auth.enterPassword': 'パスワードを入力',
    'auth.rememberMe': 'ログイン状態を保持',
    'auth.registerHere': 'こちらから登録',
    'auth.loginHere': 'こちらからログイン',
    'auth.loggingIn': 'ログイン中...',
    'auth.registering': '登録中...',
    'auth.confirmPassword': 'パスワード確認',
    'auth.enterConfirmPassword': 'パスワードを再入力',
    'auth.agreeTerms': '同意します',
    'auth.userAgreement': '利用規約',
    'auth.privacyPolicy': 'プライバシーポリシー',
    'auth.smartCitySolution': 'スマートシティソリューション',
    'auth.smartCityDesc': '革新的な技術統合を通じて生活の質を向上させるスマート都市エコシステムを構築。',
    'auth.learnMore': '詳しく見る',
    'auth.enterName': '山田太郎',
    'auth.emailPlaceholder': 'email@stengg.com',
    
    // Products
    'products.title': '製品',
    'products.featured': 'おすすめ製品',
    'products.all': 'すべての製品',
    'products.buy': '購入',
    'products.sell': '売却',
    'products.price': '価格',
    'products.status.available': '在庫あり',
    'products.status.sold': '売却済み',
    'products.status.pending': '保留中',
    
    // Profile
    'profile.title': 'マイプロフィール',
    'profile.balance': '残高',
    'profile.totalIncome': '総収入',
    'profile.transactionHistory': '取引履歴',
    'profile.depositWithdraw': '入金/出金',
    'profile.trade': '売買',
    
    // Transactions
    'transaction.deposit': '入金',
    'transaction.withdraw': '出金',
    'transaction.buy': '購入',
    'transaction.sell': '売却',
    'transaction.pending': '処理中',
    'transaction.approved': '完了',
    'transaction.rejected': '拒否',
    'transaction.amount': '金額',
    'transaction.network': 'ネットワーク',
    'transaction.walletAddress': 'ウォレットアドレス',
    'transaction.noTransactions': '取引履歴なし',
    
    // News
    'news.title': 'ニュース',
    'news.latest': '最新ニュース',
    'news.readMore': '続きを読む',
    'news.views': '閲覧',
    'news.comments': 'コメント',
    'news.writeComment': 'コメントを書く...',
    
    // Charity
    'charity.title': 'チャリティプログラム',
    'charity.progress': '進捗',
    'charity.target': '目標',
    'charity.current': '募金額',
    'charity.ongoing': '進行中',
    'charity.ended': '終了',
    'deposit.title': '入金',
    'deposit.confirm': '入金確認',
    'withdraw.title': '出金',
    'withdraw.confirm': '出金確認',
    'news.searchPlaceholder': 'ニュースを検索...',
    'news.noResults': 'ニュースが見つかりません',
    'products.noProducts': '製品がありません',
    'notFound.title': '404',
    'notFound.message': 'ページが見つかりません',
    'notFound.backHome': 'ホームに戻る',
    // Guest Home
    'guest.heroTitle': 'ST Engineering @ シンガポール・エアショー 2026',
    'guest.heroSubtitle': '次世代のイノベーションを推進',
    'guest.techTitle': '次世代イノベーションを形作るテクノロジー',
    'guest.techDesc': 'ST Engineeringは、航空宇宙、スマートシティ、防衛、公共安全など多様な事業ポートフォリオを持つグローバルなテクノロジー、防衛、エンジニアリンググループです。私たちはテクノロジーとイノベーションを活用して現実の問題を解決し、より安全で持続可能な世界を実現します。',
    'guest.aiTitle': 'AIの力で変革を実現',
    'guest.aiDesc': 'ST EngineeringはAI変革ロードマップを通じて、AI対応組織への旅を開始しました。',
    'guest.aiDesc2': '航空宇宙での予知保全からスマートアーバンソリューション、高度な防衛システムまで、AIは私たちのイノベーション戦略の中心です。',
    'guest.readMore': '続きを読む',
    'guest.enablingFuture': 'イノベーションの未来を切り開く',
    'guest.aviation': '航空の未来を形作る',
    'guest.aviationDesc': '航空機整備から革新的な航空宇宙ソリューションまで、私たちは航空の未来を牽引しています。',
    'guest.cities': '都市の未来',
    'guest.citiesDesc': '都市生活を変革し、明日のための持続可能なコミュニティを創造するスマートシティソリューション。',
    'guest.security': '共に明日を守る',
    'guest.securityDesc': '進化する世界で最も重要なものを守る高度な防衛・セキュリティソリューション。',
    'guest.ctaTitle': '境界を押し広げ、革新的なソリューションを提供',
    'guest.ctaDesc': 'グローバル統合エンジニアリンググループとして、テクノロジーとイノベーションを活用して産業を変革し、生活を改善します。航空宇宙からスマートシティ、防衛から公共安全まで、最先端のソリューションを提供します。',
    'guest.discover': 'ソリューションを見る',
    'guest.aiInnovation': 'AI駆動のイノベーションで未来を開拓',
    'guest.smartCityTitle': 'AI駆動のスマートシティインフラ',
    'guest.smartCityDesc': '人工知能を活用して、世界中の都市住民の効率性、持続可能性、生活の質を向上させるインテリジェントな都市インフラを構築。',
    'guest.cybersecurity': 'サイバーセキュリティイノベーション',
    'guest.cybersecurityTitle': 'AIでサイバーセキュリティ運用を強化',
    'guest.cybersecurityDesc': '重要インフラを保護し、進化するデジタル脅威からリアルタイムで防御する高度なAI駆動サイバーセキュリティソリューション。',
    'guest.careersTitle': '偉大なものの一部になろう',
    'guest.careersDesc': 'イノベーションが目的と出会うST Engineeringに参加しませんか。違いを生み出すことに情熱を持つ才能ある人材を求めています。',
    'guest.viewCareers': '求人を見る',
    'guest.newsTitle': 'ニュースとアップデート',
    'guest.innovation': 'イノベーション',
    'guest.news1Title': 'ST Engineering Aerospaceがシンガポール・エアショー2026に出展',
    'guest.news2Title': 'ST EngineeringのAIソリューションがイノベーション賞を受賞',
    'guest.news3Title': 'アジアのスマートシティ開発を推進する新たなパートナーシップ',
    'guest.pavilionBooth': 'シンガポールパビリオンブース（ホール3）',
    'guest.eventDate': '日程：2026年2月6日〜11日（金〜火）',
    'guest.hallStand': 'ブース位置',
    // Guest Header/Footer
    'guest.global': 'グローバル',
    'guest.contact': 'お問い合わせ',
    'guest.support': 'サポート',
    'guest.aboutUs': '会社概要',
    'guest.ourBusinesses': '事業内容',
    'guest.investorRelations': '投資家情報',
    'guest.sustainability': 'サステナビリティ',
    'guest.newsroom': 'ニュースルーム',
    'guest.careers': '採用情報',
    'guest.footerDescription': 'グローバル・テクノロジー・防衛・エンジニアリング・グループ',
    'guest.companyOverview': '会社概要',
    'guest.leadership': '経営陣',
    'guest.aerospace': '航空宇宙',
    'guest.smartCity': 'スマートシティ',
    'guest.defence': '防衛・公共安全',
    'guest.digitalSystems': 'デジタルシステム',
    'guest.contactUs': 'お問い合わせ',
    'guest.copyright': '© 2026 ST Engineering. All rights reserved.',
    'guest.termsOfUse': '利用規約',
    // Profile
    'profile.copy': 'コピー',
    'profile.copied': 'コピーしました',
    'profile.account': 'アカウント',
    'profile.security': 'セキュリティ',
    'profile.verification': '認証',
    'profile.system': 'システム',
    'profile.sync': 'データ同期',
    'profile.uidCopied': 'UIDをコピーしました',
    'profile.customerService': 'サポート',
    'profile.settings': '設定',
    'profile.invite': '友達を招待',
    'profile.update': '更新',
    'profile.securityNotice': 'パスワードやOTPを他人に教えないでください',
    
    // Settings
    'settings.language': '言語',
    'settings.currency': '通貨',
    'settings.exchangeRate': '為替レート',
  },
  ko: {
    // Common
    'common.loading': '로딩 중...',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.confirm': '확인',
    'common.delete': '삭제',
    'common.edit': '편집',
    'common.add': '추가',
    'common.search': '검색',
    'common.filter': '필터',
    'common.all': '전체',
    'common.viewAll': '전체 보기',
    'common.back': '뒤로',
    'common.close': '닫기',
    'common.submit': '제출',
    'common.status': '상태',
    'common.details': '세부사항',
    'common.copy': '복사',
    'common.settings': '설정',
    'common.processing': '처리 중...',
    'common.error': '오류가 발생했습니다',
    'common.copied': '복사됨',
    
    // Navigation
    'nav.home': '홈',
    'nav.products': '제품',
    'nav.news': '뉴스',
    'nav.charity': '자선',
    'nav.profile': '프로필',
    'nav.deposit': '입금',
    'nav.withdraw': '출금',
    'nav.dashboard': '대시보드',
    'nav.logout': '로그아웃',
    'nav.login': '로그인',
    
    // Auth
    'auth.login': '로그인',
    'auth.register': '회원가입',
    'auth.email': '이메일',
    'auth.password': '비밀번호',
    'auth.fullName': '이름',
    'auth.forgotPassword': '비밀번호를 잊으셨나요?',
    'auth.noAccount': '계정이 없으신가요?',
    'auth.hasAccount': '이미 계정이 있으신가요?',
    'auth.welcomeTitle': 'ST Engineering에 오신 것을 환영합니다',
    'auth.welcomeSubtitle': '좋은 경험이 되길 바랍니다',
    'auth.internalPortal': '내부 포털',
    'auth.loginByPhone': '전화번호로 로그인',
    'auth.loginByEmail': '이메일로 로그인',
    'auth.registerByPhone': '전화번호로 가입',
    'auth.registerByEmail': '이메일로 가입',
    'auth.phone': '전화번호',
    'auth.enterEmail': '이메일 입력',
    'auth.enterPhone': '전화번호 입력',
    'auth.enterPassword': '비밀번호 입력',
    'auth.rememberMe': '로그인 상태 유지',
    'auth.registerHere': '여기서 가입하세요',
    'auth.loginHere': '여기서 로그인하세요',
    'auth.loggingIn': '로그인 중...',
    'auth.registering': '가입 중...',
    'auth.confirmPassword': '비밀번호 확인',
    'auth.enterConfirmPassword': '비밀번호 다시 입력',
    'auth.agreeTerms': '동의합니다',
    'auth.userAgreement': '이용약관',
    'auth.privacyPolicy': '개인정보처리방침',
    'auth.smartCitySolution': '스마트 시티 솔루션',
    'auth.smartCityDesc': '혁신적인 기술 통합을 통해 삶의 질을 향상시키는 스마트 도시 생태계 구축.',
    'auth.learnMore': '자세히 보기',
    'auth.enterName': '홍길동',
    'auth.emailPlaceholder': 'email@stengg.com',
    
    // Products
    'products.title': '제품',
    'products.featured': '추천 제품',
    'products.all': '전체 제품',
    'products.buy': '구매',
    'products.sell': '판매',
    'products.price': '가격',
    'products.status.available': '구매 가능',
    'products.status.sold': '판매 완료',
    'products.status.pending': '대기 중',
    
    // Profile
    'profile.title': '내 프로필',
    'profile.balance': '잔액',
    'profile.totalIncome': '총 수입',
    'profile.transactionHistory': '거래 내역',
    'profile.depositWithdraw': '입금/출금',
    'profile.trade': '매매',
    
    // Transactions
    'transaction.deposit': '입금',
    'transaction.withdraw': '출금',
    'transaction.buy': '구매',
    'transaction.sell': '판매',
    'transaction.pending': '처리 중',
    'transaction.approved': '완료',
    'transaction.rejected': '거부됨',
    'transaction.amount': '금액',
    'transaction.network': '네트워크',
    'transaction.walletAddress': '지갑 주소',
    'transaction.noTransactions': '거래 내역 없음',
    
    // News
    'news.title': '뉴스',
    'news.latest': '최신 뉴스',
    'news.readMore': '더 보기',
    'news.views': '조회',
    'news.comments': '댓글',
    'news.writeComment': '댓글 작성...',
    
    // Charity
    'charity.title': '자선 프로그램',
    'charity.progress': '진행률',
    'charity.target': '목표',
    'charity.current': '모금액',
    'charity.ongoing': '진행 중',
    'charity.ended': '종료',
    'deposit.title': '입금',
    'deposit.confirm': '입금 확인',
    'withdraw.title': '출금',
    'withdraw.confirm': '출금 확인',
    'news.searchPlaceholder': '뉴스 검색...',
    'news.noResults': '뉴스를 찾을 수 없습니다',
    'products.noProducts': '제품이 없습니다',
    'notFound.title': '404',
    'notFound.message': '페이지를 찾을 수 없습니다',
    'notFound.backHome': '홈으로 돌아가기',
    // Guest Home
    'guest.heroTitle': 'ST Engineering @ 싱가포르 에어쇼 2026',
    'guest.heroSubtitle': '차세대 혁신을 추진',
    'guest.techTitle': '차세대 혁신을 형성하는 기술',
    'guest.techDesc': 'ST Engineering은 항공우주, 스마트 시티, 국방 및 공공 안전 분야에서 다양한 사업 포트폴리오를 보유한 글로벌 기술, 국방 및 엔지니어링 그룹입니다. 우리는 기술과 혁신을 활용하여 실제 문제를 해결하고 더 안전하고 지속 가능한 세상을 만듭니다.',
    'guest.aiTitle': 'AI의 힘으로 변화를 이끌다',
    'guest.aiDesc': 'ST Engineering은 AI 변환 로드맵을 통해 AI 기반 조직으로의 여정을 시작했습니다.',
    'guest.aiDesc2': '항공우주의 예측 유지보수부터 스마트 도시 솔루션 및 첨단 국방 시스템까지, AI는 우리 혁신 전략의 핵심입니다.',
    'guest.readMore': '더 읽기',
    'guest.enablingFuture': '혁신의 미래를 열다',
    'guest.aviation': '항공의 미래를 형성',
    'guest.aviationDesc': '항공기 정비에서 혁신적인 항공우주 솔루션까지, 우리는 비행의 미래를 선도합니다.',
    'guest.cities': '도시의 미래',
    'guest.citiesDesc': '도시 생활을 변화시키고 내일을 위한 지속 가능한 커뮤니티를 만드는 스마트 시티 솔루션.',
    'guest.security': '함께 내일을 지키다',
    'guest.securityDesc': '진화하는 세계에서 가장 중요한 것을 보호하는 첨단 국방 및 보안 솔루션.',
    'guest.ctaTitle': '한계를 넘어 혁신적인 솔루션 제공',
    'guest.ctaDesc': '글로벌 통합 엔지니어링 그룹으로서 기술과 혁신을 활용하여 산업을 변화시키고 삶을 개선합니다. 항공우주에서 스마트 시티, 국방에서 공공 안전까지 최첨단 솔루션을 제공합니다.',
    'guest.discover': '솔루션 살펴보기',
    'guest.aiInnovation': 'AI 기반 혁신으로 미래 개척',
    'guest.smartCityTitle': 'AI 기반 스마트 시티 인프라',
    'guest.smartCityDesc': '인공지능을 활용하여 전 세계 도시 주민의 효율성, 지속 가능성 및 삶의 질을 향상시키는 지능형 도시 인프라 구축.',
    'guest.cybersecurity': '사이버 보안 혁신',
    'guest.cybersecurityTitle': 'AI로 사이버 보안 운영 강화',
    'guest.cybersecurityDesc': '중요 인프라를 보호하고 진화하는 디지털 위협으로부터 실시간으로 방어하는 첨단 AI 기반 사이버 보안 솔루션.',
    'guest.careersTitle': '위대한 일의 일부가 되세요',
    'guest.careersDesc': '혁신과 목적이 만나는 ST Engineering에 합류하세요. 변화를 만드는 데 열정을 가진 재능 있는 인재를 찾고 있습니다.',
    'guest.viewCareers': '채용 공고 보기',
    'guest.newsTitle': '뉴스 및 업데이트',
    'guest.innovation': '혁신',
    'guest.news1Title': 'ST Engineering Aerospace가 싱가포르 에어쇼 2026에 출전',
    'guest.news2Title': 'ST Engineering의 AI 솔루션이 혁신상 수상',
    'guest.news3Title': '아시아 스마트 시티 개발을 촉진하는 새로운 파트너십',
    'guest.pavilionBooth': '싱가포르 파빌리온 부스 (홀 3)',
    'guest.eventDate': '날짜: 2026년 2월 6-11일 (금-화)',
    'guest.hallStand': '부스 위치',
    // Guest Header/Footer
    'guest.global': '글로벌',
    'guest.contact': '연락처',
    'guest.support': '지원',
    'guest.aboutUs': '회사 소개',
    'guest.ourBusinesses': '사업 영역',
    'guest.investorRelations': '투자자 관계',
    'guest.sustainability': '지속가능성',
    'guest.newsroom': '뉴스룸',
    'guest.careers': '채용',
    'guest.footerDescription': '글로벌 기술, 국방 및 엔지니어링 그룹',
    'guest.companyOverview': '회사 개요',
    'guest.leadership': '경영진',
    'guest.aerospace': '항공우주',
    'guest.smartCity': '스마트 시티',
    'guest.defence': '국방 및 공공 안전',
    'guest.digitalSystems': '디지털 시스템',
    'guest.contactUs': '문의하기',
    'guest.copyright': '© 2026 ST Engineering. 모든 권리 보유.',
    'guest.termsOfUse': '이용약관',
    // Profile
    'profile.copy': '복사',
    'profile.copied': '복사됨',
    'profile.account': '계정',
    'profile.security': '보안',
    'profile.verification': '인증',
    'profile.system': '시스템',
    'profile.sync': '데이터 동기화',
    'profile.uidCopied': 'UID 복사됨',
    'profile.customerService': '고객 지원',
    'profile.settings': '설정',
    'profile.invite': '친구 초대',
    'profile.update': '업데이트',
    'profile.securityNotice': '비밀번호나 OTP를 다른 사람에게 알려주지 마세요',
    
    // Settings
    'settings.language': '언어',
    'settings.currency': '통화',
    'settings.exchangeRate': '환율',
  },
  id: {
    // Common
    'common.loading': 'Memuat...',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.confirm': 'Konfirmasi',
    'common.delete': 'Hapus',
    'common.edit': 'Edit',
    'common.add': 'Tambah',
    'common.search': 'Cari',
    'common.filter': 'Filter',
    'common.all': 'Semua',
    'common.viewAll': 'Lihat Semua',
    'common.back': 'Kembali',
    'common.close': 'Tutup',
    'common.submit': 'Kirim',
    'common.status': 'Status',
    'common.details': 'Detail',
    'common.copy': 'Salin',
    'common.settings': 'Pengaturan',
    'common.processing': 'Memproses...',
    'common.error': 'Terjadi kesalahan',
    'common.copied': 'Disalin',
    
    // Navigation
    'nav.home': 'Beranda',
    'nav.products': 'Produk',
    'nav.news': 'Berita',
    'nav.charity': 'Amal',
    'nav.profile': 'Profil',
    'nav.deposit': 'Setor',
    'nav.withdraw': 'Tarik',
    'nav.dashboard': 'Dasbor',
    'nav.logout': 'Keluar',
    'nav.login': 'Masuk',
    
    // Auth
    'auth.login': 'Masuk',
    'auth.register': 'Daftar',
    'auth.email': 'Email',
    'auth.password': 'Kata Sandi',
    'auth.fullName': 'Nama Lengkap',
    'auth.forgotPassword': 'Lupa kata sandi?',
    'auth.noAccount': 'Belum punya akun?',
    'auth.hasAccount': 'Sudah punya akun?',
    'auth.welcomeTitle': 'Selamat datang di ST Engineering',
    'auth.welcomeSubtitle': 'Semoga pengalaman Anda menyenangkan',
    'auth.internalPortal': 'Portal Internal',
    'auth.loginByPhone': 'Masuk dengan Telepon',
    'auth.loginByEmail': 'Masuk dengan Email',
    'auth.registerByPhone': 'Daftar dengan Telepon',
    'auth.registerByEmail': 'Daftar dengan Email',
    'auth.phone': 'Nomor Telepon',
    'auth.enterEmail': 'Masukkan email Anda',
    'auth.enterPhone': 'Masukkan nomor telepon Anda',
    'auth.enterPassword': 'Masukkan kata sandi Anda',
    'auth.rememberMe': 'Ingat saya',
    'auth.registerHere': 'Daftar di sini',
    'auth.loginHere': 'Masuk di sini',
    'auth.loggingIn': 'Sedang masuk...',
    'auth.registering': 'Sedang mendaftar...',
    'auth.confirmPassword': 'Konfirmasi Kata Sandi',
    'auth.enterConfirmPassword': 'Masukkan ulang kata sandi',
    'auth.agreeTerms': 'Saya setuju dengan',
    'auth.userAgreement': 'Perjanjian Pengguna',
    'auth.privacyPolicy': 'Kebijakan Privasi',
    'auth.smartCitySolution': 'Solusi Kota Pintar',
    'auth.smartCityDesc': 'Membangun ekosistem kota pintar yang meningkatkan kualitas hidup melalui integrasi teknologi inovatif.',
    'auth.learnMore': 'Pelajari lebih lanjut',
    'auth.enterName': 'Budi Santoso',
    'auth.emailPlaceholder': 'email@stengg.com',
    
    // Products
    'products.title': 'Produk',
    'products.featured': 'Produk Unggulan',
    'products.all': 'Semua Produk',
    'products.buy': 'Beli',
    'products.sell': 'Jual',
    'products.price': 'Harga',
    'products.status.available': 'Tersedia',
    'products.status.sold': 'Terjual',
    'products.status.pending': 'Tertunda',
    
    // Profile
    'profile.title': 'Profil Saya',
    'profile.balance': 'Saldo',
    'profile.totalIncome': 'Total Pendapatan',
    'profile.transactionHistory': 'Riwayat Transaksi',
    'profile.depositWithdraw': 'Setor/Tarik',
    'profile.trade': 'Jual/Beli',
    
    // Transactions
    'transaction.deposit': 'Setor',
    'transaction.withdraw': 'Tarik',
    'transaction.buy': 'Beli',
    'transaction.sell': 'Jual',
    'transaction.pending': 'Menunggu',
    'transaction.approved': 'Selesai',
    'transaction.rejected': 'Ditolak',
    'transaction.amount': 'Jumlah',
    'transaction.network': 'Jaringan',
    'transaction.walletAddress': 'Alamat Dompet',
    'transaction.noTransactions': 'Belum ada transaksi',
    
    // News
    'news.title': 'Berita',
    'news.latest': 'Berita Terbaru',
    'news.readMore': 'Baca Selengkapnya',
    'news.views': 'dilihat',
    'news.comments': 'Komentar',
    'news.writeComment': 'Tulis komentar...',
    
    // Charity
    'charity.title': 'Program Amal',
    'charity.progress': 'Progres',
    'charity.target': 'Target',
    'charity.current': 'Terkumpul',
    'charity.ongoing': 'Sedang Berjalan',
    'charity.ended': 'Berakhir',
    'deposit.title': 'Setor',
    'deposit.confirm': 'Konfirmasi Setor',
    'withdraw.title': 'Tarik',
    'withdraw.confirm': 'Konfirmasi Penarikan',
    'news.searchPlaceholder': 'Cari berita...',
    'news.noResults': 'Berita tidak ditemukan',
    'products.noProducts': 'Tidak ada produk',
    'notFound.title': '404',
    'notFound.message': 'Halaman tidak ditemukan',
    'notFound.backHome': 'Kembali ke Beranda',
    // Guest Home
    'guest.heroTitle': 'ST Engineering @ Singapore Airshow 2026',
    'guest.heroSubtitle': 'Mendorong inovasi generasi berikutnya',
    'guest.techTitle': 'Teknologi yang membentuk inovasi generasi berikutnya',
    'guest.techDesc': 'ST Engineering adalah grup teknologi, pertahanan, dan rekayasa global dengan portofolio bisnis yang beragam di bidang dirgantara, kota pintar, pertahanan, dan keamanan publik. Kami memanfaatkan teknologi dan inovasi untuk memecahkan masalah dunia nyata, menciptakan dunia yang lebih aman dan berkelanjutan.',
    'guest.aiTitle': 'Menggerakkan perubahan dengan kekuatan AI',
    'guest.aiDesc': 'ST Engineering telah memulai perjalanan untuk menjadi organisasi yang didukung AI melalui peta jalan transformasi AI kami.',
    'guest.aiDesc2': 'Dari pemeliharaan prediktif di dirgantara hingga solusi perkotaan pintar dan sistem pertahanan canggih, AI adalah inti dari strategi inovasi kami.',
    'guest.readMore': 'Baca Selengkapnya',
    'guest.enablingFuture': 'Membuka masa depan inovasi',
    'guest.aviation': 'Membentuk masa depan Penerbangan',
    'guest.aviationDesc': 'Dari pemeliharaan pesawat hingga solusi dirgantara inovatif, kami memimpin masa depan penerbangan.',
    'guest.cities': 'MASA DEPAN KOTA',
    'guest.citiesDesc': 'Solusi kota pintar yang mengubah kehidupan perkotaan dan menciptakan komunitas berkelanjutan untuk masa depan.',
    'guest.security': 'Mengamankan hari esok, bersama',
    'guest.securityDesc': 'Solusi pertahanan dan keamanan canggih yang melindungi hal-hal terpenting di dunia yang terus berkembang.',
    'guest.ctaTitle': 'Mendorong batas untuk memberikan solusi revolusioner',
    'guest.ctaDesc': 'Sebagai grup rekayasa terintegrasi global, kami memanfaatkan teknologi dan inovasi untuk mengubah industri dan meningkatkan kehidupan. Dari dirgantara ke kota pintar, pertahanan ke keamanan publik, kami memberikan solusi mutakhir.',
    'guest.discover': 'Jelajahi solusi kami',
    'guest.aiInnovation': 'Merintis masa depan dengan inovasi bertenaga AI',
    'guest.smartCityTitle': 'Infrastruktur Kota Pintar Berbasis AI',
    'guest.smartCityDesc': 'Memanfaatkan kecerdasan buatan untuk menciptakan infrastruktur perkotaan cerdas yang meningkatkan efisiensi, keberlanjutan, dan kualitas hidup bagi penduduk kota di seluruh dunia.',
    'guest.cybersecurity': 'Inovasi Keamanan Siber',
    'guest.cybersecurityTitle': 'Memperkuat Operasi Keamanan Siber dengan AI',
    'guest.cybersecurityDesc': 'Solusi keamanan siber canggih bertenaga AI yang melindungi infrastruktur kritis dan bertahan melawan ancaman digital yang terus berkembang secara real-time.',
    'guest.careersTitle': 'Jadilah bagian dari sesuatu yang besar',
    'guest.careersDesc': 'Bergabunglah dengan kami di ST Engineering, tempat inovasi bertemu dengan tujuan. Kami mencari individu berbakat yang bersemangat untuk membuat perbedaan.',
    'guest.viewCareers': 'Lihat Karir',
    'guest.newsTitle': 'Berita dan Pembaruan',
    'guest.innovation': 'Inovasi',
    'guest.news1Title': 'ST Engineering Aerospace akan tampil di Singapore Airshow 2026',
    'guest.news2Title': 'Solusi AI ST Engineering meraih Penghargaan Inovasi',
    'guest.news3Title': 'Kemitraan baru mendorong pengembangan kota pintar di Asia',
    'guest.pavilionBooth': 'Booth Pavilion Singapura (Hall 3)',
    'guest.eventDate': 'Tanggal: 6-11 Feb 2026 (Jum-Sel)',
    'guest.hallStand': 'Posisi Booth',
    // Guest Header/Footer
    'guest.global': 'Global',
    'guest.contact': 'Kontak',
    'guest.support': 'Dukungan',
    'guest.aboutUs': 'Tentang Kami',
    'guest.ourBusinesses': 'Bisnis Kami',
    'guest.investorRelations': 'Hubungan Investor',
    'guest.sustainability': 'Keberlanjutan',
    'guest.newsroom': 'Ruang Berita',
    'guest.careers': 'Karir',
    'guest.footerDescription': 'Grup teknologi, pertahanan, dan rekayasa global.',
    'guest.companyOverview': 'Gambaran Perusahaan',
    'guest.leadership': 'Kepemimpinan',
    'guest.aerospace': 'Dirgantara',
    'guest.smartCity': 'Kota Pintar',
    'guest.defence': 'Pertahanan & Keamanan Publik',
    'guest.digitalSystems': 'Sistem Digital',
    'guest.contactUs': 'Hubungi Kami',
    'guest.copyright': '© 2026 ST Engineering. Hak cipta dilindungi.',
    'guest.termsOfUse': 'Syarat Penggunaan',
    // Profile
    'profile.copy': 'Salin',
    'profile.copied': 'Disalin',
    'profile.account': 'Akun',
    'profile.security': 'Keamanan',
    'profile.verification': 'Verifikasi',
    'profile.system': 'Sistem',
    'profile.sync': 'Sinkronisasi Data',
    'profile.uidCopied': 'UID disalin',
    'profile.customerService': 'Dukungan',
    'profile.settings': 'Pengaturan',
    'profile.invite': 'Undang Teman',
    'profile.update': 'Perbarui',
    'profile.securityNotice': 'Jangan bagikan kata sandi atau OTP Anda kepada siapa pun',
    
    // Settings
    'settings.language': 'Bahasa',
    'settings.currency': 'Mata Uang',
    'settings.exchangeRate': 'Kurs',
  },
  ms: {
    // Common
    'common.loading': 'Memuatkan...',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.confirm': 'Sahkan',
    'common.delete': 'Padam',
    'common.edit': 'Edit',
    'common.add': 'Tambah',
    'common.search': 'Cari',
    'common.filter': 'Tapis',
    'common.all': 'Semua',
    'common.viewAll': 'Lihat Semua',
    'common.back': 'Kembali',
    'common.close': 'Tutup',
    'common.submit': 'Hantar',
    'common.status': 'Status',
    'common.details': 'Butiran',
    'common.copy': 'Salin',
    'common.settings': 'Tetapan',
    'common.processing': 'Memproses...',
    'common.error': 'Ralat berlaku',
    'common.copied': 'Disalin',
    
    // Navigation
    'nav.home': 'Laman Utama',
    'nav.products': 'Produk',
    'nav.news': 'Berita',
    'nav.charity': 'Amal',
    'nav.profile': 'Profil',
    'nav.deposit': 'Deposit',
    'nav.withdraw': 'Pengeluaran',
    'nav.dashboard': 'Papan Pemuka',
    'nav.logout': 'Log Keluar',
    'nav.login': 'Log Masuk',
    
    // Auth
    'auth.login': 'Log Masuk',
    'auth.register': 'Daftar',
    'auth.email': 'E-mel',
    'auth.password': 'Kata Laluan',
    'auth.fullName': 'Nama Penuh',
    'auth.forgotPassword': 'Lupa kata laluan?',
    'auth.noAccount': 'Belum ada akaun?',
    'auth.hasAccount': 'Sudah ada akaun?',
    'auth.welcomeTitle': 'Selamat datang ke ST Engineering',
    'auth.welcomeSubtitle': 'Semoga pengalaman anda menyenangkan',
    'auth.internalPortal': 'Portal Dalaman',
    'auth.loginByPhone': 'Log masuk dengan Telefon',
    'auth.loginByEmail': 'Log masuk dengan E-mel',
    'auth.registerByPhone': 'Daftar dengan Telefon',
    'auth.registerByEmail': 'Daftar dengan E-mel',
    'auth.phone': 'Nombor Telefon',
    'auth.enterEmail': 'Masukkan e-mel anda',
    'auth.enterPhone': 'Masukkan nombor telefon anda',
    'auth.enterPassword': 'Masukkan kata laluan anda',
    'auth.rememberMe': 'Ingat saya',
    'auth.registerHere': 'Daftar di sini',
    'auth.loginHere': 'Log masuk di sini',
    'auth.loggingIn': 'Sedang log masuk...',
    'auth.registering': 'Sedang mendaftar...',
    'auth.confirmPassword': 'Sahkan Kata Laluan',
    'auth.enterConfirmPassword': 'Masukkan semula kata laluan',
    'auth.agreeTerms': 'Saya bersetuju dengan',
    'auth.userAgreement': 'Perjanjian Pengguna',
    'auth.privacyPolicy': 'Dasar Privasi',
    'auth.smartCitySolution': 'Penyelesaian Bandar Pintar',
    'auth.smartCityDesc': 'Membina ekosistem bandar pintar yang meningkatkan kualiti hidup melalui integrasi teknologi inovatif.',
    'auth.learnMore': 'Ketahui lebih lanjut',
    'auth.enterName': 'Ahmad bin Ali',
    'auth.emailPlaceholder': 'email@stengg.com',
    
    // Products
    'products.title': 'Produk',
    'products.featured': 'Produk Pilihan',
    'products.all': 'Semua Produk',
    'products.buy': 'Beli',
    'products.sell': 'Jual',
    'products.price': 'Harga',
    'products.status.available': 'Tersedia',
    'products.status.sold': 'Terjual',
    'products.status.pending': 'Tertangguh',
    
    // Profile
    'profile.title': 'Profil Saya',
    'profile.balance': 'Baki',
    'profile.totalIncome': 'Jumlah Pendapatan',
    'profile.transactionHistory': 'Sejarah Transaksi',
    'profile.depositWithdraw': 'Deposit/Pengeluaran',
    'profile.trade': 'Jual/Beli',
    
    // Transactions
    'transaction.deposit': 'Deposit',
    'transaction.withdraw': 'Pengeluaran',
    'transaction.buy': 'Beli',
    'transaction.sell': 'Jual',
    'transaction.pending': 'Menunggu',
    'transaction.approved': 'Selesai',
    'transaction.rejected': 'Ditolak',
    'transaction.amount': 'Jumlah',
    'transaction.network': 'Rangkaian',
    'transaction.walletAddress': 'Alamat Dompet',
    'transaction.noTransactions': 'Tiada transaksi lagi',
    
    // News
    'news.title': 'Berita',
    'news.latest': 'Berita Terkini',
    'news.readMore': 'Baca Lagi',
    'news.views': 'tontonan',
    'news.comments': 'Komen',
    'news.writeComment': 'Tulis komen...',
    
    // Charity
    'charity.title': 'Program Amal',
    'charity.progress': 'Kemajuan',
    'charity.target': 'Sasaran',
    'charity.current': 'Terkumpul',
    'charity.ongoing': 'Sedang Berjalan',
    'charity.ended': 'Tamat',
    'deposit.title': 'Deposit',
    'deposit.confirm': 'Sahkan Deposit',
    'withdraw.title': 'Pengeluaran',
    'withdraw.confirm': 'Sahkan Pengeluaran',
    'news.searchPlaceholder': 'Cari berita...',
    'news.noResults': 'Berita tidak dijumpai',
    'products.noProducts': 'Tiada produk',
    'notFound.title': '404',
    'notFound.message': 'Halaman tidak dijumpai',
    'notFound.backHome': 'Kembali ke Laman Utama',
    // Guest Home
    'guest.heroTitle': 'ST Engineering @ Singapore Airshow 2026',
    'guest.heroSubtitle': 'Memacu inovasi generasi seterusnya',
    'guest.techTitle': 'Teknologi yang membentuk inovasi generasi seterusnya',
    'guest.techDesc': 'ST Engineering adalah kumpulan teknologi, pertahanan dan kejuruteraan global dengan portfolio perniagaan yang pelbagai merangkumi aeroangkasa, bandar pintar, pertahanan dan keselamatan awam. Kami memanfaatkan teknologi dan inovasi untuk menyelesaikan masalah dunia sebenar, mewujudkan dunia yang lebih selamat dan mampan.',
    'guest.aiTitle': 'Memacu perubahan dengan kuasa AI',
    'guest.aiDesc': 'ST Engineering telah memulakan perjalanan untuk menjadi organisasi yang didayakan AI melalui peta jalan transformasi AI kami.',
    'guest.aiDesc2': 'Dari penyelenggaraan ramalan dalam aeroangkasa hingga penyelesaian bandar pintar dan sistem pertahanan canggih, AI adalah teras strategi inovasi kami.',
    'guest.readMore': 'Baca Lagi',
    'guest.enablingFuture': 'Membuka masa depan inovasi',
    'guest.aviation': 'Membentuk masa depan Penerbangan',
    'guest.aviationDesc': 'Dari penyelenggaraan pesawat hingga penyelesaian aeroangkasa inovatif, kami memacu masa depan penerbangan.',
    'guest.cities': 'MASA DEPAN BANDAR',
    'guest.citiesDesc': 'Penyelesaian bandar pintar yang mengubah kehidupan bandar dan mencipta komuniti mampan untuk masa depan.',
    'guest.security': 'Mengamankan hari esok, bersama',
    'guest.securityDesc': 'Penyelesaian pertahanan dan keselamatan canggih yang melindungi perkara paling penting dalam dunia yang berubah.',
    'guest.ctaTitle': 'Menolak sempadan untuk menyampaikan penyelesaian revolusioner',
    'guest.ctaDesc': 'Sebagai kumpulan kejuruteraan bersepadu global, kami memanfaatkan teknologi dan inovasi untuk mengubah industri dan meningkatkan kehidupan. Dari aeroangkasa ke bandar pintar, pertahanan ke keselamatan awam, kami menyampaikan penyelesaian canggih.',
    'guest.discover': 'Terokai penyelesaian kami',
    'guest.aiInnovation': 'Merintis masa depan dengan inovasi berkuasa AI',
    'guest.smartCityTitle': 'Infrastruktur Bandar Pintar Didorong AI',
    'guest.smartCityDesc': 'Memanfaatkan kecerdasan buatan untuk mencipta infrastruktur bandar pintar yang meningkatkan kecekapan, kemampanan dan kualiti hidup bagi penduduk bandar di seluruh dunia.',
    'guest.cybersecurity': 'Inovasi Keselamatan Siber',
    'guest.cybersecurityTitle': 'Memperkasa Operasi Keselamatan Siber dengan AI',
    'guest.cybersecurityDesc': 'Penyelesaian keselamatan siber canggih berkuasa AI yang melindungi infrastruktur kritikal dan mempertahankan daripada ancaman digital yang berkembang secara masa nyata.',
    'guest.careersTitle': 'Jadilah sebahagian daripada sesuatu yang hebat',
    'guest.careersDesc': 'Sertai kami di ST Engineering, di mana inovasi bertemu tujuan. Kami mencari individu berbakat yang bersemangat untuk membuat perbezaan.',
    'guest.viewCareers': 'Lihat Kerjaya',
    'guest.newsTitle': 'Berita dan Kemas Kini',
    'guest.innovation': 'Inovasi',
    'guest.news1Title': 'ST Engineering Aerospace akan mempamerkan di Singapore Airshow 2026',
    'guest.news2Title': 'Penyelesaian AI ST Engineering memenangi Anugerah Inovasi',
    'guest.news3Title': 'Perkongsian baharu untuk memajukan pembangunan bandar pintar di Asia',
    'guest.pavilionBooth': 'Gerai Pavilion Singapura (Dewan 3)',
    'guest.eventDate': 'Tarikh: 6-11 Feb 2026 (Jum-Sel)',
    'guest.hallStand': 'Lokasi Gerai',
    // Guest Header/Footer
    'guest.global': 'Global',
    'guest.contact': 'Hubungi',
    'guest.support': 'Sokongan',
    'guest.aboutUs': 'Tentang Kami',
    'guest.ourBusinesses': 'Perniagaan Kami',
    'guest.investorRelations': 'Hubungan Pelabur',
    'guest.sustainability': 'Kelestarian',
    'guest.newsroom': 'Bilik Berita',
    'guest.careers': 'Kerjaya',
    'guest.footerDescription': 'Kumpulan teknologi, pertahanan dan kejuruteraan global.',
    'guest.companyOverview': 'Gambaran Syarikat',
    'guest.leadership': 'Kepimpinan',
    'guest.aerospace': 'Aeroangkasa',
    'guest.smartCity': 'Bandar Pintar',
    'guest.defence': 'Pertahanan & Keselamatan Awam',
    'guest.digitalSystems': 'Sistem Digital',
    'guest.contactUs': 'Hubungi Kami',
    'guest.copyright': '© 2026 ST Engineering. Hak cipta terpelihara.',
    'guest.termsOfUse': 'Terma Penggunaan',
    // Profile
    'profile.copy': 'Salin',
    'profile.copied': 'Disalin',
    'profile.account': 'Akaun',
    'profile.security': 'Keselamatan',
    'profile.verification': 'Pengesahan',
    'profile.system': 'Sistem',
    'profile.sync': 'Segerakkan Data',
    'profile.uidCopied': 'UID disalin',
    'profile.customerService': 'Sokongan',
    'profile.settings': 'Tetapan',
    'profile.invite': 'Jemput Rakan',
    'profile.update': 'Kemas Kini',
    'profile.securityNotice': 'Jangan kongsi kata laluan atau OTP anda dengan sesiapa',
    
    // Settings
    'settings.language': 'Bahasa',
    'settings.currency': 'Mata Wang',
    'settings.exchangeRate': 'Kadar Pertukaran',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });
  const [isTransitioning, setIsTransitioning] = useState(false);

  const setLanguage = (lang: Language) => {
    if (lang === language) return;
    
    setIsTransitioning(true);
    
    // Brief fade out, then change language, then fade in
    setTimeout(() => {
      setLanguageState(lang);
      localStorage.setItem('language', lang);
      
      setTimeout(() => {
        setIsTransitioning(false);
      }, 50);
    }, 150);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isTransitioning }}>
      <div 
        className={`transition-opacity duration-150 ${isTransitioning ? 'opacity-0' : 'opacity-100'}`}
      >
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
