ALTER TABLE public.charity_programs
  ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS cycle_days INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS interest_rate NUMERIC NOT NULL DEFAULT 0;